# Q8.
```{admonition}
:class: note
A formula for calculating PVE is given below.
$$    
\frac{\sum_{i=1}^{n} z_{im}^{2}}{\sum_{j=1}^{p}\sum_{i=1}^{n} x_{ij}^{2}} = \frac{\sum_{i=1}^{n} \left(\sum_{j=1}^{p} \varphi_{jm}x_{ij}\right)^{2}}{\sum_{j=1}^{p}\sum_{i=1}^{n} x_{ij}^{2}}
$$
The PVE can also be obtained using the `explained_variance_ratio_` attribute of a fitted `PCA()` estimator. On the `USArrests` data, calculate PVE in two ways:

In [2]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [ ]:
arrests = pd.read_csv('../../../ALL CSV FILES - 2nd Edition/USArrests.csv',index_col=0)

## (a)
```{admonition}
:class: note
Using the `explained_variance_ratio_` output of the fitted `PCA()` estimator.

In [4]:
scaler = StandardScaler()
arrests_scale = pd.DataFrame(scaler.fit_transform(arrests),columns=arrests.columns,index=arrests.index)

In [5]:
arrests_pca = PCA()
arrests_pca.fit(arrests_scale)
print(arrests_pca.explained_variance_ratio_)

[0.62006039 0.24744129 0.0891408  0.04335752]


## (b)
```{admonition}
:class: note
By applying the equation directly.

In [6]:
denom = np.sum(arrests_scale**2)
print(np.array([np.sum(np.sum(arrests_scale.values * arrests_pca.components_[m,:],axis=1)**2)/denom for m in range(4)]))

[0.62006039 0.24744129 0.0891408  0.04335752]


In [7]:
print(np.sum(np.dot(arrests_scale,arrests_pca.components_.T)**2,axis=0)/np.sum(arrests_scale**2))

[0.62006039 0.24744129 0.0891408  0.04335752]
